services:
  - type: web
    name: video2text
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: "sh -c 'uvicorn app:app --host 0.0.0.0 --port $PORT'"
    envVars:
      - key: PORT
        value: "8000"
